export const STORE_CREATE_TASK_DATA = 'tasks/STORE_CREATE_TASK_DATA';
export const STORE_SELECTED_TASK_ID = 'tasks/STORE_SELECTED_TASK_ID';
export const CREATE_TASK_REQUEST = 'tasks/CREATE_TASK_REQUEST';
export const CREATE_TASK_SUCCESS = 'tasks/CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAILURE = 'tasks/CREATE_TASK_FAILURE';
